In [1]:
print("Hello World!!!")


Hello World!!!


In [15]:
import torch
from pprint import pprint
print(torch.__version__)

2.9.0+cu126


In [3]:
print(torch.cuda.is_available())

if torch.cuda.is_available():
    print("CUDA is available. You can use GPU for computations.")
else:
    print("ONly CPU is available.")

True
CUDA is available. You can use GPU for computations.


# Tensor

Columns vs Depth

1. Columns (2D Context)
When dealing with a Rank-2 tensor (a matrix), the structure is defined by (Rows, Columns).

Axis: Usually Axis 1.
Visual: Think of a spreadsheet. The columns run vertically, but you count them across the horizontal axis.
Use Case: Features in a dataset, pixels in a single row of a grayscale image.


2. Depth (3D Context)
When dealing with a Rank-3 tensor (a cube or volume), the structure is often (Height, Width, Depth) or (Rows, Columns, Depth).

Axis: Usually Axis 2 (in "channels_last" convention).
Visual: Think of a stack of spreadsheets or matrices behind one another.
Use Case:
Color Channels: In an RGB image, the depth is 3 (Red, Green, Blue layers).
Filters: In Convolutional Neural Networks (CNNs), depth represents the number of feature maps.
# 3d tensor image like structure
3. Height vs. Depth
Height: A spatial dimension. It defines the physical size or resolution of the data vertically.

In [26]:
# empty tensor - nd matrix

a = torch.empty(4, 2) # 4 rows and 2 columns
b = torch.zeros(4, 2, 5) # 4 rows, 2 columns and 5 depth
c = torch.zeros(2, 3, 4, 5) # 2 rows, 3 columns and 4 depth and 5 height
print(a)
# print(b)
#c

# columns vs depth 

tensor([[7.1514e-16, 0.0000e+00],
        [7.1509e-16, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])


In [ ]:
type(a) # torch.Tensor

torch.Tensor

In [46]:
torch.zeros(1, 2, 3)
torch.ones(1, 2, 3)

torch.manual_seed(42) # pre defined value of seed for data reproducibility in torch.rand
torch.rand(1, 2, 3) # random value between 0 and 1

tensor([[[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]]])

In [ ]:
tf_tensor = torch.tensor([[1, 2, 3], [0.1, 0.2, 0.3], [True, False, True], [4, 5, 6]]) # excel sheet like structure

tf_tensor_1 = torch.tensor([ [[1, 2, 3], [0.1, 0.2, 0.3], [True, False, True], [4, 5, 6]], [[1, 2, 3], [0.1, 0.2, 0.3], [True, False, True], [4, 5, 6]]]) 
# 3d tensor image like structure


print(tf_tensor)
print(type(tf_tensor))
print(tf_tensor.dtype)
print(tf_tensor.shape)

print("<-- -->")
print(tf_tensor_1)
print(type(tf_tensor_1))
print(tf_tensor_1.dtype)
print(tf_tensor_1.shape)

tensor([[1.0000, 2.0000, 3.0000],
        [0.1000, 0.2000, 0.3000],
        [1.0000, 0.0000, 1.0000],
        [4.0000, 5.0000, 6.0000]])
<class 'torch.Tensor'>
torch.float32
torch.Size([4, 3])
<-- -->
tensor([[[1.0000, 2.0000, 3.0000],
         [0.1000, 0.2000, 0.3000],
         [1.0000, 0.0000, 1.0000],
         [4.0000, 5.0000, 6.0000]],

        [[1.0000, 2.0000, 3.0000],
         [0.1000, 0.2000, 0.3000],
         [1.0000, 0.0000, 1.0000],
         [4.0000, 5.0000, 6.0000]]])
<class 'torch.Tensor'>
torch.float32
torch.Size([2, 4, 3])
